spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        - id: gy_user_route
          uri: lb://gy-user
          predicates:
#              - Host=cloud.gy.com**
          - Path=/api/**
          filters:
#               - PrefixPath=/brand
          - StripPrefix=1
          - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 10
  redis:
    host: 127.0.0.1
    port: 7000

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true