server:
  port: 9003

spring:
  profiles:
    active: dev
  application:
    name: gy-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    prefer-ip-address: true
