eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  server:
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是60*1000）
  client:
    registerWithEureka: false # 不注册自己
    fetchRegistry: false      #不拉取服务
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF